name: Endless Meadow CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install raylib
        run: |
          brew update
          brew install raylib cmake

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Zip macOS app
        run: |
          cd build
          zip -r EndlessMeadow-macOS.zip EndlessMeadow.app

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: EndlessMeadow-macOS
          path: build/EndlessMeadow-macOS.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install raylib
        run: |
          git clone https://github.com/raysan5/raylib.git
          cd raylib
          cmake -B build
          cmake --build build --config Release
          cmake --install build

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: EndlessMeadow-Windows
          path: build

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libraylib-dev \
            cmake \
            g++ \
            xorg-dev \
            libgl1-mesa-dev \
            libasound2-dev

      - name: Configure
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: EndlessMeadow-Linux
          path: build
